name: C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug
  INSTALL_LOCATION: ".local"

jobs:
  gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install google test and boost, also install g++-11
        run: sudo apt-get install libgtest-dev googletest googletest-tools google-mock g++-11
      - name: Checkout repository
        with:
          submodules: recursive
        uses: actions/checkout@v3
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: CMake Lib release config
        run: cmake -S . -B release -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=Release
      - name: CMake Lib release build
        run: cmake --build release
      - name: CMake Lib debug config
        run: cmake -S . -B debug -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=Debug
      - name: CMake Lib debug build
        run: cmake --build debug
      - name: Run tests
        run: debug/zip_in_cpp_tests

  clang:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install google test and boost, also install clang-15
        run: sudo apt-get install libgtest-dev googletest googletest-tools google-mock clang-15
      - name: Checkout repository
        with:
          submodules: recursive
        uses: actions/checkout@v3
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: CMake Lib release config
        run: cmake -S . -B release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
      - name: CMake Lib release build
        run: cmake --build release
      - name: CMake Lib debug config
        run: cmake -S . -B debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
      - name: CMake Lib debug build
        run: cmake --build debug
      - name: Run tests
        run: debug/zip_in_cpp_tests
